version: '3.4'

services:
  trustnetwork.webapi:
    image: ${DOCKER_REGISTRY-}trustnetworkwebapi
    restart: always
    build:
      context: .
      dockerfile: src/TrustNetwork.WebAPI/Dockerfile
    depends_on:
      - db
  db:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    restart: always
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "S3cur3P@ssW0rd!"
      ACCEPT_EULA: "Y"